steps = [
    [
        # "Up" SQL statement
        """--sql
            CREATE TABLE cities (
                id SERIAL PRIMARY KEY NOT NULL,
                name VARCHAR(100) NOT NULL,
                administrative_division VARCHAR(200),
                country VARCHAR(100),
                picture_url VARCHAR(300),
                description TEXT,
                UNIQUE(name, country)
            );
        """,
        # "Down" SQL statement
        """--sql
            DROP TABLE cities;
        """,
    ],
    [
        """--sql
            INSERT INTO cities (name, administrative_division, country, picture_url, description)
            VALUES
            ('Bangkok', 'Bangkok', 'Thailand', 'https://www.indochinatravelpackages.com/wp-content/uploads/2015/07/Bangkok.jpeg', 'Bangkok is an energetic mix of old and new, where ancient temples meet bustling markets and towering skyscrapers. Visit the iconic Grand Palace, or take a stroll through Chatuchak Market. For nightlife, head to Khao San Road, filled with lively bars, street food vendors, and backpackers.'),
            ('Paris', 'Île-de-France', 'France', 'https://cdn.britannica.com/31/255531-050-B7E07090/eiffel-tower-paris-france-champ-de-mars-view.jpg', 'Paris is synonymous with romance, art, and gastronomy. Stroll along the Seine, marvel at the Eiffel Tower, or explore the art-filled Louvre Museum. The city’s café culture is unmatched—grab a croissant and coffee while watching the world go by.'),
            ('London', 'England', 'United Kingdom', 'https://i0.wp.com/wheelchairtravel.org/wp-content/uploads/2020/01/london-v2020-header-scaled.jpg', 'London is a sprawling city at the center of everything: art, history, culture—you name it. But what sets it apart from other major hubs are its distinct neighborhoods, each with their own vibe. Spend an afternoon in Kensington for museums and parks, or explore edgy Shoreditch for street art and cool shops.'),
            ('Dubai', 'Dubai', 'United Arab Emirates', 'https://www.theglobetrottingdetective.com/wp-content/uploads/2021/01/Dubai-in-7-days-and-best-things-to-do-in-Dubai-.jpg', 'Dubai is a city of futuristic skylines, luxury shopping, and world-class attractions. Visit the Burj Khalifa, the tallest building in the world, or explore the souks for a taste of traditional culture. Dubai’s beaches offer a perfect escape from the city’s desert heat.'),
            ('Singapore', 'Central Region', 'Singapore', 'https://worldstrides.com/wp-content/uploads/2015/07/0001_SG-Now.jpg', 'Singapore is a high-tech, cosmopolitan city with a green heart. Explore Gardens by the Bay, a futuristic botanical garden, or shop along Orchard Road. The city’s hawker centers offer a taste of local flavor, from chili crab to Hainanese chicken rice.'),
            ('New York City', 'New York', 'United States', 'https://www.hertz.com/content/dam/hertz/global/blog-articles/things-to-do/best-things-to-do-in-new-york/nyc-things-to-do-1.jpg', 'New York City is the city that never sleeps, where skyscrapers meet street-level culture. Walk through Central Park, catch a Broadway show, or shop in SoHo. The food scene is unbeatable, from street-side pizza to Michelin-starred dining.'),
            ('Kuala Lumpur', 'Federal Territory of Kuala Lumpur', 'Malaysia', 'https://www.agoda.com/wp-content/uploads/2024/01/Featured-image-KL-city-at-night-1244x700.jpg', 'Kuala Lumpur blends modernity and tradition with ease. The Petronas Towers dominate the skyline, while street markets, temples, and mosques showcase the city’s rich cultural heritage. For a local experience, explore the Batu Caves or shop in Bukit Bintang.'),
            ('Tokyo', 'Tokyo Metropolis', 'Japan', 'https://media.cntraveller.com/photos/6343df288d5d266e2e66f082/16:9/w_1280,c_limit/tokyoGettyImages-1031467664.jpeg', 'Tokyo is a sprawling metropolis where ancient traditions meet cutting-edge technology. Visit the Meiji Shrine for a taste of Japan’s spiritual side, or dive into the bustling streets of Shibuya. Tokyo’s food scene is world-famous, from sushi to ramen to Michelin-star restaurants.'),
            ('Istanbul', 'Istanbul Province', 'Turkey', 'https://www.civitatis.com/blog/wp-content/uploads/2024/03/shutterstock_291252509-1920x1248.jpg', 'Istanbul is where East meets West, a city that bridges continents and cultures. Explore the Hagia Sophia, the Blue Mosque, and the bustling Grand Bazaar. The Bosphorus Strait offers stunning views, while the city’s lively street food scene offers a taste of local flavors like kebabs and baklava.'),
            ('Antalya', 'Antalya Province', 'Turkey', 'https://cdn.travelatelier.com/wp-content/uploads/2019/05/10-unforgettable-things-to-do-antalya-turkey.jpg', 'Antalya is a sun-soaked Mediterranean gem, famous for its beaches, ancient ruins, and scenic harbor. Explore the old town of Kaleiçi, or take a boat tour along the Turquoise Coast. The region’s mountains and waterfalls provide plenty of adventure for outdoor lovers.'),
            ('Seoul', 'Seoul', 'South Korea', 'https://media.nomadicmatt.com/2022/koreaguide1.jpg', 'Seoul is a dynamic city where the past and present coexist. Visit the historic Gyeongbokgung Palace, then head to the ultra-modern district of Gangnam. Street food stalls, karaoke bars, and bustling markets ensure there’s never a dull moment in this vibrant capital.'),
            ('Osaka', 'Osaka Prefecture', 'Japan', 'https://japancitytour.com/wp-content/uploads/2019/08/osaka-castle.jpeg', 'Osaka is Japan’s kitchen, known for its food scene and welcoming vibe. Visit the iconic Osaka Castle, or explore Dotonbori, a neon-lit district packed with restaurants and street food vendors. Don’t miss trying takoyaki, the city’s famous octopus-filled snack.'),
            ('Makkah', 'Makkah Province', 'Saudi Arabia', 'https://mediaim.expedia.com/destination/1/574dfc983d34cf0ca1ffb20a45aca0de.jpg', 'Makkah is the holiest city in Islam, drawing millions of pilgrims each year for the Hajj. The Masjid al-Haram, home to the Kaaba, is the spiritual center of the city. Beyond its religious significance, Makkah also offers stunning mountain views and a peaceful, reflective atmosphere.'),
            ('Phuket', 'Phuket Province', 'Thailand', 'https://res.klook.com/image/upload/Mobile/City/p2pfj38lzjf7wsd6gobn.jpg', 'Phuket is Thailand’s largest island, known for its stunning beaches, vibrant nightlife, and rich culture. Explore the bustling streets of Patong, or take a boat tour to the nearby Phi Phi Islands. For a more tranquil experience, visit the Big Buddha and soak in the panoramic views.'),
            ('Pattaya', 'Chonburi Province', 'Thailand', 'https://www.agoda.com/wp-content/uploads/2024/02/Featured-image-Aerial-view-of-Pattaya-Thailand-1244x700.jpg', 'Pattaya is famous for its lively nightlife and beachfront fun. By day, explore the nearby islands or relax on the beach, and by night, experience the neon-lit streets filled with bars and clubs. For families, the Sanctuary of Truth and Nong Nooch Tropical Garden offer a more peaceful retreat.'),
            ('Hong Kong', 'Hong Kong Island', 'Hong Kong', 'https://cdn.i-scmp.com/sites/default/files/d8/images/canvas/2024/03/08/2e0c9793-9c10-494d-861d-e8ca9b89d22e_e89e7a52.jpg', 'Hong Kong is a bustling metropolis known for its skyline, vibrant harbor, and street markets. Take a ride on the Star Ferry, visit the iconic Victoria Peak, or explore the bustling streets of Kowloon. The food scene ranges from dim sum to world-class Michelin-starred restaurants.'),
            ('Milan', 'Lombardy', 'Italy', 'https://media.cntraveller.com/photos/656dfc28341940048b149e58/master/w_1600%2Cc_limit/Shopping_Milan_2_December23_GettyImages-1669837323.jpg', 'Milan is Italy’s fashion and design capital, but there’s much more to discover here. Visit the Duomo di Milano, shop in the luxurious Galleria Vittorio Emanuele II, or explore the art scene at the Pinacoteca di Brera. Milan’s food scene includes everything from classic Italian pasta to modern cuisine.'),
            ('Barcelona', 'Catalonia', 'Spain', 'https://www.berlinsbi.com/uploads/sites/2/2023/06/web-banner-barcelona.jpg', 'Barcelona is a city of art, architecture, and beachside relaxation. Wander through the streets of the Gothic Quarter, marvel at Gaudí’s iconic Sagrada Família, or relax on the sands of Barceloneta Beach. The food scene offers everything from tapas to Michelin-starred dining.'),
            ('Rome', 'Lazio', 'Italy', 'https://www.fodors.com/wp-content/uploads/2018/10/HERO_UltimateRome_Hero_shutterstock789412159.jpg', 'Rome is a city of ancient history and modern charm. Explore the ruins of the Roman Forum, toss a coin in the Trevi Fountain, or marvel at the beauty of St. Peter’s Basilica. For food, indulge in classic Italian dishes like pasta carbonara and gelato.'),
            ('Bali', 'Bali', 'Indonesia', 'https://www.holidify.com/images/bgImages/BALI.jpg', 'Bali is a tropical paradise known for its beaches, temples, and vibrant culture. Relax on the sands of Seminyak, explore the rice terraces of Ubud, or visit the ancient Pura Ulun Danu Bratan temple. Bali’s wellness retreats and yoga studios also draw visitors seeking relaxation and rejuvenation.'),
            ('Las Vegas', 'Nevada', 'United States', 'https://vegasexperience.com/wp-content/uploads/2023/01/Photo-of-Las-Vegas-Downtown-1920x1280.jpg', 'Las Vegas is a neon-lit playground in the desert, famous for its casinos, world-class entertainment, and over-the-top resorts. Stroll down the Strip to see iconic landmarks like the Bellagio fountains and the replica Eiffel Tower, or catch a show from some of the biggest names in entertainment. But beyond the glitz, you’ll find fine dining, luxury shopping, and outdoor adventures in nearby Red Rock Canyon.'),
            ('Shanghai', 'Shanghai Municipality', 'China', 'https://img-cdn-china-admissions.imgix.net/wp-content/uploads/2021/03/Shanghai.jpg', 'Shanghai is China’s largest city, a futuristic metropolis known for its towering skyline, historic architecture, and bustling waterfront. Walk along the Bund for stunning views of the Huangpu River, or visit the historic Yu Garden for a taste of the city’s ancient past. Don’t miss the vibrant neighborhoods like the French Concession or the ultra-modern Pudong district.'),
            ('Amsterdam', 'North Holland', 'Netherlands', 'https://www.cunard.com/content/dam/cunard/inventory-assets/ports/AMS/AMS.jpg', 'Amsterdam is a city of canals, culture, and creativity. Cycle through the cobbled streets, visit world-famous museums like the Van Gogh Museum or Rijksmuseum, and relax in one of the city’s many cozy cafés. Amsterdam’s laid-back vibe is matched by its vibrant nightlife and diverse food scene.'),
            ('Vienna', 'Vienna', 'Austria', 'https://media.nomadicmatt.com/2023/viennathreeday.jpeg', 'Vienna is a city of grand palaces, classical music, and elegant cafés. Visit Schönbrunn Palace, the former imperial summer residence, or wander through the narrow streets of the historic old town. Vienna’s café culture is legendary, and the city’s coffeehouses are the perfect place to indulge in a slice of Sachertorte.'),
            ('Los Angeles', 'California', 'United States', 'https://i.natgeofe.com/n/f7145fb3-d6ad-41bb-8065-1d7312e72bf4/hollywood-boulevard-los-angeles-california.jpg', 'Los Angeles is a sprawling city of palm trees, beaches, and Hollywood glamour. Hike up to the Griffith Observatory for stunning views of the city and the iconic Hollywood sign, or spend a day at one of LA’s famous beaches like Venice or Santa Monica. The city’s diverse neighborhoods, from artsy Downtown to the star-studded hills of Beverly Hills, offer something for everyone.'),
            ('Madrid', 'Community of Madrid', 'Spain', 'https://www.fodors.com/wp-content/uploads/2021/07/UltimateMadrid__HERO_shutterstock_374325199.jpg', 'Madrid is a lively city known for its art, culture, and nightlife. Visit the Prado Museum to see masterpieces by Goya and Velázquez, or stroll through the grand plazas like Puerta del Sol and Plaza Mayor. Madrid’s tapas scene is a must-try, offering everything from traditional Spanish dishes to modern culinary creations.'),
            ('Berlin', 'Berlin', 'Germany', 'https://www.fodors.com/wp-content/uploads/2024/07/0_HERO_istock_1340628888.jpg', 'Berlin is a city of contrasts, where history and modernity collide. Visit the Berlin Wall Memorial or the Brandenburg Gate to delve into the city’s turbulent past, or explore the trendy neighborhoods of Kreuzberg and Friedrichshain for cutting-edge art and nightlife. Berlin is also known for its unique food scene, from street food markets to Michelin-starred restaurants.'),
            ('Prague', 'Prague', 'Czech Republic', 'https://www.fodors.com/wp-content/uploads/2018/10/9_PragueGhostHunting__VysehradSoldier_dreamstime_xl_36037710_2.jpg', 'Prague is a fairy-tale city of cobblestone streets, Gothic spires, and medieval charm. Walk across the iconic Charles Bridge, visit the magnificent Prague Castle, or explore the old town square with its famous astronomical clock. The city’s beer culture is legendary, so be sure to stop by a local pub for a pint of Czech lager.'),
            ('Miami', 'Florida', 'United States', 'https://www.fodors.com/wp-content/uploads/2018/11/9_MiamiManyPersonalities_Luxury_aerial-3_2.jpg', 'Miami is where sun, sand, and style meet. Spend the day lounging on South Beach, known for its Art Deco architecture and vibrant nightlife, or explore the colorful neighborhoods of Little Havana and Wynwood. Miami’s diverse food scene, blending Cuban, Caribbean, and Latin flavors, is not to be missed.'),
            ('Munich', 'Bavaria', 'Germany', 'https://www.fodors.com/wp-content/uploads/2018/08/iStock-637088124.jpg', 'Munich is a city of beer gardens, baroque architecture, and Bavarian charm. Visit Marienplatz, the heart of the city, or explore the historic Nymphenburg Palace. Munich is home to Oktoberfest, the world’s largest beer festival, but its beer gardens and hearty food can be enjoyed year-round.'),
            ('Florence', 'Tuscany', 'Italy', 'https://www.fodors.com/wp-content/uploads/2019/08/UltimateTuscany__HERO_cpuiQ-OV.jpg', 'Florence is the birthplace of the Renaissance, a city filled with art, history, and charm. Visit the Uffizi Gallery to see works by Michelangelo and Botticelli, or marvel at the iconic Duomo. Florence’s narrow streets are lined with cafés and shops, offering a perfect blend of culture and relaxation.'),
            ('Sydney', 'New South Wales', 'Australia', 'https://www.fodors.com/wp-content/uploads/2019/07/UltimateSydney__HERO_iStock-646880230.jpg', 'Sydney is Australia’s largest city, famous for its stunning harbor, iconic Opera House, and laid-back beach lifestyle. Explore the vibrant neighborhoods of Surry Hills and Newtown, or take a ferry ride to Manly Beach for surf and sun. The city’s diverse food scene reflects its multicultural roots.'),
            ('Buenos Aires', 'Autonomous City of Buenos Aires', 'Argentina', 'https://www.fodors.com/wp-content/uploads/2018/08/Hero-Reasons-To-Visit-Buenos-Aires-shutterstock_404805433-1.jpg', 'Buenos Aires is a city of passion, tango, and European charm. Explore the colorful streets of La Boca, visit the iconic Recoleta Cemetery, or watch a tango show in one of the city’s historic venues. Buenos Aires is also known for its steak and wine, making it a haven for food lovers.'),
            ('San Francisco', 'California', 'United States', 'https://www.fodors.com/wp-content/uploads/2019/10/shutterstock_107079455-2048x1365.jpg', 'San Francisco is a city of hills, fog, and iconic landmarks. Walk across the Golden Gate Bridge, explore the lively streets of Chinatown, or take a ride on a historic cable car. San Francisco’s food scene is a blend of global flavors, from fresh seafood to inventive farm-to-table cuisine.'),
            ('Mexico City', 'Mexico City', 'Mexico', 'https://www.fodors.com/wp-content/uploads/2022/04/shutterstock_1005708952.jpg', 'Mexico City is a bustling metropolis of history, art, and culture. Visit the ancient pyramids of Teotihuacan, explore the Frida Kahlo Museum, or stroll through Chapultepec Park. The city’s food scene is world-renowned, with everything from street-side tacos to high-end dining experiences.'),
            ('Moscow', 'Moscow', 'Russia', 'https://www.fodors.com/wp-content/uploads/2019/02/08_RussiaHoneymoon__Russiaisnotwhatitseems_shutterstock_570337246.jpg', 'Moscow is a city of grandeur and history, home to iconic landmarks like the Kremlin and Red Square. Explore the city’s historic cathedrals, stroll through Gorky Park, or take a ride on the city’s impressive metro system. Moscow’s food scene offers a blend of traditional Russian dishes and modern cuisine.'),
            ('Toronto', 'Ontario', 'Canada', 'https://www.fodors.com/wp-content/uploads/2022/05/1-TAKETHEKIDS-ULTTORONTO-shutterstock_551287744.jpg', 'Toronto is Canada’s largest city, a multicultural hub of arts, culture, and cuisine. Visit the iconic CN Tower for panoramic views of the city, or explore the vibrant neighborhoods of Kensington Market and the Distillery District. Toronto’s food scene reflects its diverse population, offering a world of flavors.'),
            ('Orlando', 'Florida', 'United States', 'https://www.fodors.com/wp-content/uploads/2024/04/0_HERO_istock_1368286105.jpg', 'Orlando is best known as the theme park capital of the world, home to Walt Disney World, Universal Studios, and more. Beyond the parks, explore the city’s lively downtown area, filled with restaurants, shops, and entertainment. Orlando’s warm weather and family-friendly attractions make it a top destination.'),
            ('Rio de Janeiro', 'Rio de Janeiro', 'Brazil', 'https://www.fodors.com/wp-content/uploads/2022/07/HERO-shutterstock_1283692720.jpg', 'Rio de Janeiro is a city of samba, sun, and stunning scenery. Relax on the iconic Copacabana Beach, take a cable car up Sugarloaf Mountain, or visit the Christ the Redeemer statue for panoramic views of the city. Rio’s vibrant culture, lively nightlife, and carnival spirit make it a must-visit.'),
            ('Beijing', 'Beijing Municipality', 'China', 'https://www.fodors.com/wp-content/uploads/2019/03/HERO_Beijing_Museums_shutterstock_257936231.jpg', 'Beijing is a city of contrasts, where ancient history meets modern architecture. Walk through the Forbidden City, visit the majestic Great Wall, or explore the bustling streets of Wangfujing. Beijing’s rich cultural heritage is matched by its diverse food scene, from Peking duck to street food delicacies.'),
            ('Cape Town', 'Western Cape', 'South Africa', 'https://www.fodors.com/wp-content/uploads/2016/05/48HrsCapeTown-hero.jpg', 'Cape Town is a city of natural beauty, where Table Mountain towers over sandy beaches and vibrant neighborhoods. Take a hike up the mountain for breathtaking views, visit Robben Island, or explore the lively waterfront. Cape Town’s blend of cultures is reflected in its food and art, making it a dynamic destination.'),
            ('Lisbon', 'Lisbon District', 'Portugal', 'https://www.fodors.com/wp-content/uploads/2024/02/0-HERO-Shutterstock-254435464.jpg', 'Lisbon is a charming city of hills, pastel-colored buildings, and historic tram lines. Visit the ancient Belém Tower, explore the narrow streets of Alfama, or ride the famous Tram 28 for stunning views of the city. Lisbon’s relaxed vibe and vibrant nightlife make it a perfect destination for travelers seeking both culture and fun.'),
            ('Venice', 'Veneto', 'Italy', 'https://www.fodors.com/wp-content/uploads/2023/06/0-HERO-istockphoto-1388018793.jpg', 'Venice is a city like no other, where canals replace streets and gondolas glide past Renaissance architecture. Visit St. Mark’s Basilica, explore the narrow alleyways, or take a ride down the Grand Canal. Venice’s timeless beauty and romantic charm have made it a top destination for centuries.'),
            ('Brussels', 'Brussels', 'Belgium', 'https://www.fodors.com/wp-content/uploads/2023/11/0-HERO-istockphoto-513065348.jpg', 'Brussels is a city of grand squares, delicious waffles, and world-famous chocolate. Explore the majestic Grand Place, visit the Atomium, or stroll through the city’s many parks and museums. Brussels’ blend of French and Flemish cultures gives the city a unique and diverse character.'),
            ('Cairo', 'Cairo Governorate', 'Egypt', 'https://www.fodors.com/wp-content/uploads/2022/10/CC_Luxor_Ramses_II_Statue.jpg', 'Cairo is a city of ancient wonders and modern energy, where the Pyramids of Giza stand alongside bustling bazaars and vibrant neighborhoods. Explore the treasures of the Egyptian Museum, take a boat ride down the Nile, or visit the historic mosques of Islamic Cairo. Cairo’s rich history and lively atmosphere make it a truly unforgettable destination.'),
            ('Zurich', 'Zurich', 'Switzerland', 'https://www.meganstarr.com/wp-content/uploads/2023/02/One-day-in-Zurich-itinerary_219250780.jpg', 'Zurich is Switzerland’s largest city, known for its pristine lakeside setting, high-end shopping, and efficient public transport. Visit the historic old town, explore the world-class museums, or take a boat ride on Lake Zurich. The city’s modern, clean vibe is complemented by its alpine backdrop, making it a perfect blend of urban and natural beauty.'),
            ('Mumbai', 'Maharashtra', 'India', 'https://www.micato.com/wp-content/uploads/2018/09/mumbai-6.jpg', 'Mumbai is India’s financial capital, a city of contrasts where Bollywood glamour meets bustling markets and ancient temples. Visit the iconic Gateway of India, explore the vibrant Colaba district, or take a walk along Marine Drive. Mumbai’s street food is legendary, offering everything from spicy vada pav to sweet jalebi.'),
            ('Delhi', 'National Capital Territory', 'India', 'https://www.fodors.com/wp-content/uploads/2023/11/0-HERO-Shutterstock-2183275499.jpg', 'Delhi is a city of history and modernity, where Mughal architecture stands alongside contemporary skyscrapers. Explore the Red Fort, visit the iconic India Gate, or get lost in the bustling streets of Chandni Chowk. Delhi’s food scene is a culinary adventure, offering everything from street-side chaat to gourmet dining.'),
            ('Copenhagen', 'Capital Region', 'Denmark', 'https://www.fodors.com/wp-content/uploads/2024/06/0_HERO_Shutterstock_1962600736.jpg', 'Copenhagen is a city of sleek design, rich history, and waterfront charm. Visit the crayon-colored houses of Nyhavn, explore the historic Tivoli Gardens, or take a bike ride through the city’s many parks. Copenhagen’s culinary scene is world-renowned, with Michelin-star restaurants reinventing Nordic cuisine.');
        """,
        """--sql
            DROP TABLE cities;
        """,
    ],
]
